/// <reference types="vite/client"/>
declare module '@/store/user/useUserStore'
declare module '@/store/index'
declare module '@/routes/core/guard/isNotLogged'
declare module '@/routes/core/guard/isLogged'
declare module '@/routes/routes'
declare module '@/types/user'

declare module '@/screens/galery'
declare module '@/screens/generate'
declare module '@/screens/userProfile'
declare module '@/screens/objectProfile'
declare module '@/screens/login'
declare module '@/screens/register'
declare module '@/screens/askCredentials'
declare module '@/screens/sent'
declare module '@/screens/test'

declare module '@/modules/galery/components/searcher'
declare module '@/modules/generate/components/inputFile'
